#!/usr/bin/env python3
"""Freeze the approved Desktop tokens/artwork for the isolated credential page.

No cross-repository dependency at worker runtime. Run --check during design QA.
"""
import argparse
import hashlib
import json
import re
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
desktop = root.parent / "yijie-desktop"
page = root / "worker/src/credentials"
source = (desktop / "src/styles/variables.css").read_text()
light, dark = source.split('[data-theme="dark"] {', 1)
declarations = lambda text: dict(re.findall(r"(--yj-[\w-]+):\s*([^;]+);", text))
light, dark = declarations(light), declarations(dark)
used = set(re.findall(r"var\((--yj-[\w-]+)\)", (page / "page.css").read_text()))
while True:
    nested = set()
    for name in used:
        nested.update(re.findall(r"var\((--yj-[\w-]+)\)", light[name]))
        nested.update(re.findall(r"var\((--yj-[\w-]+)\)", dark.get(name, "")))
    if nested <= used:
        break
    used |= nested

def block(values):
    return "\n".join(f"  {name}: {values[name]};" for name in sorted(used) if name in values)

tokens = "/* Generated by scripts/sync-credential-design.py; canonical Desktop tokens. */\n"
tokens += ":root {\n  color-scheme: light;\n" + block(light) + "\n}\n"
tokens += "@media (prefers-color-scheme: dark) {\n:root {\n  color-scheme: dark;\n" + block(dark) + "\n}\n}\n"
outputs = {"tokens.css": tokens.encode()}
sources = ["src/styles/variables.css"]
for path in ["src/assets/brand/yijie-mark.svg", "src/assets/brand/yijie-mark-dark.svg", "src/assets/connectors/sorftime.svg"]:
    outputs[Path(path).name] = (desktop / path).read_bytes()
    sources.append(path)
outputs["provenance.json"] = (json.dumps({
    "sourceRepository": "yijie-desktop",
    "sources": {path: hashlib.sha256((desktop / path).read_bytes()).hexdigest() for path in sources},
    "note": "Approved artwork copied unchanged; referenced design tokens projected for system light/dark theme."
}, ensure_ascii=False, indent=2) + "\n").encode()
directory = page / "assets"
if not args.check:
    directory.mkdir(exist_ok=True)
for name, content in outputs.items():
    target = directory / name
    if args.check:
        if not target.exists() or target.read_bytes() != content:
            raise SystemExit(f"Credential design snapshot differs: {name}")
    else:
        target.write_bytes(content)
print("Credential design snapshot matches Desktop" if args.check else "Credential design snapshot updated")
